### ISSUE TITLE
It must be installed on the server

### ISSUE THREAD

**Issue by Hieso** [APeng215/FiltPick#14]
Can you please try to make sure that you don't have to install this mod on the server.

**Comment by APeng215** [comment]
Someone asked a similar question before. The answer is:
> It seems impossible: 
Item-pick logic is handled automatically on the server side, not on client side. So you must make sure that the server you join has installed the mod, only then the pick-filt logic could be implemented.

from https://github.com/APeng215/FiltPick/issues/7#issuecomment-1569729131.
