### ISSUE TITLE
Server crashing on Fabric 1.20.1 Filtpick

### ISSUE THREAD

**Issue by p0nx77** [APeng215/FiltPick#8]
Hi, so I added the mod on both clients and server side for Fabric 1.20.1. 

The server started fine. However when anyone tries to click the filtpick button, the server crashes. Here it is:

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2024-02-10 17:47:54
Description: Exception in server tick loop

java.lang.NoSuchFieldError: backgroundPainter
	at io.github.cottonmc.cotton.gui.widget.WPanel.<init>(WPanel.java:27)
	at io.github.cottonmc.cotton.gui.widget.WPanelWithInsets.<init>(WPanelWithInsets.java:12)
	at io.github.cottonmc.cotton.gui.widget.WGridPanel.<init>(WGridPanel.java:33)
	at io.github.cottonmc.cotton.gui.SyncedGuiDescription.<init>(SyncedGuiDescription.java:53)
	at com.apeng.filtpick.guis.custom.FiltPickGuiDescription.<init>(FiltPickGuiDescription.java:24)
	at com.apeng.filtpick.FiltPick$1.createMenu(FiltPick.java:48)
	at net.minecraft.class_3222.method_17355(class_3222.java:1034)
	at com.apeng.filtpick.FiltPick.lambda$registerC2SReceiver$0(FiltPick.java:51)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version 5.15.0-1045-oracle
	Java Version: 17.0.9, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1483511424 bytes (1414 MiB) / 2080374784 bytes (1984 MiB) up to 19327352832 bytes (18432 MiB)
	CPUs: 4
	Processor Vendor: aarch64
	Processor Name: 
	Identifier: aarch64 Family 8 Model 0xd0c Stepping r0x3p1
	Microarchitecture: unknown
	Frequency (GHz): 2.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Virtio GPU
	Graphics card #0 vendor: Red Hat, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: version: 01
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: RAM
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: RAM
	Virtual memory max (MB): 11993.94
	Virtual memory used (MB): 3118.00
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx18G
	Fabric Mods: 
		allarrowsinfinityfix: All Arrows Infinity Fix 1.4
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20.1
		another_furniture: Another Furniture 1.20.1-3.0.1
		architectury: Architectury 9.1.12
		artifacts: Artifacts 9.2.0
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.0
			porting_lib_attributes: Porting Lib Attributes 2.1.1093+1.20
				porting_lib_core: Porting Lib Core 2.1.1093+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1093+1.20
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		automobility: Automobility 0.4.2+1.20.1-fabric
			jsonem: JsonEM 0.2.1+1.20
		bakery: Bakery 1.1.3
		balm-fabric: Balm 7.2.1
		beautify: Beautify 1.1.0+1.20
		bettercombat: Better Combat 1.8.3+1.20.1
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
			org_reflections_reflections: reflections 0.10.2
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		bloomingnature: Blooming Nature 1.0.2
		bushierflowers: Bushier Flowers 0.0.3-1.20.1
		bwncr: Bad Wither No Cookie Reloaded 3.17.0
		candlelight: Candlelight 1.2.8
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carrier: Carrier 1.12.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		chimes: Chimes 2.0.1
		chunkloaders: Chunk Loaders 1.2.8+a
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.5.7
		collective: Collective 7.30
		compact_storage: Compact Storage 5.0.3_1.20.1
		coroutil: CoroUtil 1.20.1-1.3.5
		cozy: Cozy 1.1.1
		craftingpad: Crafting Pad 1.0.12
		cupboard: cupboard 1.20.1-2.2
		diagonalfences: Diagonal Fences 8.1.3
			diagonalblocks: Diagonal Blocks 8.0.2
		doapi: Lets Do Api 1.2.8
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		easyanvils: Easy Anvils 8.0.1
		elytraslot: Elytra Slot 6.3.0+1.20.1
		emojiful: Emojiful 4.2.0
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
			midnightlib: MidnightLib 1.1.0
		endrem: End Remastered 5.2.4
		essential_commands: Essential Commands 0.35.0-mc1.20.1
			ec-core: Essential Commands Core 1.3.0-mc1.20.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			org_yaml_snakeyaml: snakeyaml 2.0
			playerabilitylib: Pal 1.8.0
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-hammers: Fabric Hammers 1.2.1
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		fallingtree: FallingTree 4.3.4
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		fastasyncworldsave: fastasyncworldsave Mod 1.20.1-1.4
		ferritecore: FerriteCore 6.0.1
		filtpick: FiltPick 1.2.1
			libgui: LibGui 8.0.0-beta.1+1.20-rc1
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		flan: Flan 1.20.1-1.8.11
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		geckolib: GeckoLib 4 4.4.2
			com_eliotlash_mclib_mclib: mclib 20
		getittogetherdrops: Get It Together, Drops! fabric-1.20-1.3.1
		grapplemod: Grappling Hook Mod 1.20-v1.7
		hamsters: Hamsters 1.0.2-fabric
		handcrafted: Handcrafted 3.0.5
		healingcampfire: Healing Campfire 5.3
		immersive_aircraft: Immersive Aircraft 0.6.2+1.20.1
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		itemcollectors: Item Collectors 1.1.9
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.18
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		knavesneeds: Knaves' Needs 2.0.1+1.20.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		leavesbegone: Leaves Be Gone 8.0.0
		lithium: Lithium 0.11.2
		luphieclutteredmod: Cluttered 2.1.0+1.20.1
		magnumtorch: Magnum Torch 8.0.2
		mc2discord: Mc2Discord 4.2.3
		mcwfences: Macaw's Fences and Walls 1.1.0
		mcwroofs: Macaw's Roofs 2.2.4
		mine-spawners: mine-spawners 1.0
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.12.1+mc1.20.1
		moonlight: Moonlight 1.20-2.9.3
		movingelevators: Moving Elevators 1.4.5
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		nightlights: Night Lights 1.1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		paraglider: Paragliders 20.1.3
		pickablevillagers: Pickable Villagers 1.4.5+1.20.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.1+1.20.1
			spectrelib: SpectreLib 0.13.14+1.20.1
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		puzzleslib: Puzzles Lib 8.1.15
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		reinfbarrel: Reinforced Barrels 2.4.1+1.20
			reinfcore: Reinforced Core 3.1.2+1.20
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		right-click-harvest: Right-Click-Harvest 1.2.0
		roughlyenoughitems: Roughly Enough Items 12.0.684
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.9.0
		scarecrowsterritory: Scarecrows' Territory 1.1.11
		simplemagnets: Simple Magnets 1.1.10
		simplyswords: Simply Swords 1.51.5-1.20.1
		smarterfarmers: Smarter Farmers 1.20-1.8.0
		smoothchunk: Smooth chunk save Mod 1.20.1-3.5
		spark: spark 1.10.53
		starlight: Starlight 1.1.2+fabric.dbc156f
		structory: Structory 1.3.4
		structory_towers: Structory: Towers 1.0.6
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.20-2.7.30
			mixinsquared: MixinSquared 0.1.1
		things: Things 0.3.3+1.20
			lavender: Lavender 0.1.0-pre.18+1.20
				lavender-md: lavender-md 0.1.0-pre.3+1.20
				lavender-md-owo-ui: lavender-md-owo-ui 0.1.0-pre.3+1.20
			reach-entity-attributes: Reach Entity Attributes 2.3.3-pre.2
		toms_storage: Tom's Simple Storage Mod 1.6.5
		toofast: TooFast 1.2.0
		trade_cycling: Trade Cycling 1.20.1-1.0.7
		tradingpost: Trading Post 8.0.2
		trampledisablerfabric: Trample Disabler 1.0.8
		trashcans: Trash Cans 1.0.18
			team_reborn_energy: Energy 3.0.0
		trashslot: TrashSlot 15.1.0
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		trinkets: Trinkets 3.7.1
		universal-graves: Universal Graves 3.0.1+1.20.1
			common-protection-api: Common Protection API 1.0.0
			placeholder-api: Placeholder API 2.1.3+1.20.1
			polymer-core: Polymer (Core) 0.5.19+1.20.1
				polymer-networking: Polymer (Networking) 0.5.19+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.19+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.19+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.19+1.20.1
				polymer-common: Polymer (Common) 0.5.19+1.20.1
			predicate-api: Predicate API 0.2.1+1.20.1
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			sgui: sgui 1.2.2+1.20
		universalenchants: Universal Enchants 8.0.0
			extensibleenums: Extensible Enums 7.0.1
		variantfurnaces: Variant Furnaces 1.2.0
		vinery: Vinery 1.4.7
		visualworkbench: Visual Workbench 8.0.0
		watut: What Are They Up To 1.20.1-1.0.12
		waystones: Waystones 14.1.3
		xtraarrows: Xtra Arrows 3 3.0.4
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Server Running: true
	Player Count: 1 / 100; [class_3222['davidoque'/208, l='ServerLevel[world]', x=2901.32, y=78.00, z=-5096.40]]
	Data Packs: vanilla, Supplementaries Generated Pack, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	
	
	
	Thanks,

**Comment by APeng215** [comment]
Thank you for your feedback! 

The latest version aimed at fixing this bug has been released. You can download it [from Modrinth](https://modrinth.com/mod/filtpick/versions) or anywhere you like.

You can `close this issue as completed` yourself if the mod works properly now. Or if there are still some problems, feel free to leave more comments in this issue. I'll handle it. This issue will be closed if stays inactive for a long time.

**Comment by p0nx77** [comment]
> Thank you for your feedback!
> 
> The latest version _(FiltPick-fabric-mc1.20.1-1.2.3)_ aimed at fixing this bug has been released. You can download it [from Modrinth](https://modrinth.com/mod/filtpick/versions) or anywhere you like.
> 
> You can `close this issue as completed` yourself if the mod works properly now. Or if there are still some problems, feel free to leave more comments in this issue. I'll handle it. This issue will be closed if stays inactive for a long time.

Incredible. Thank you so much for your fast response and help. I really appreciate it! Have a great day!

**Comment by p0nx77** [comment]
and Yes, it works perfect now!
