### ISSUE TITLE
More filter slots

### ISSUE THREAD

**Issue by Razor235T** [APeng215/FiltPick#9]
With a tone of mods there are too many items dropping from mobs. Filtpick is super useful but limited because of the slots limit. My filtpick inventory is always full and I still have to drop items from inventory from time to time. Could you please extend filtpick inventory?

**Comment by Razor235T** [comment]
I wish you good luck with your exam. I am playing on minecraft 1.20.1 forge, Filtpick 0.0.2. I have a lot of mods which don't like updates, so I personally will stay on 1.20.1 version of minecraft for at least a year for sure. I'll stay tuned for the updates, and thank you for the information.

**Comment by Nuttar** [comment]
I've also just started a 1.20.1 modpack with lots worth filtering and so few options to deal with it. So i'd also like to ask for fabric version. For anyone else that comes here for this, the other non-gui option is "Item Obliterator", gotta add each block name to a text file so it's a bit of a pain.

Thanks for FiltPick regardless, Apeng215.

**Comment by degiel1982** [comment]
I was creating a modpack for fabric. Minecraft v1.20.4 i love this mod. I hope you can add more slots. Its such a usefull tool

**Comment by APeng215** [comment]
***FiltPick-forge-mc1.20.1-0.1.0*** has been released, now featuring four times the filter space and a scrolling feature. I am currently working on synchronizing these features with the latest version (1.21.1 or later). For older versions, I may selectively update features if time permits.

**Comment by Razor235T** [comment]
Thanks, all works well. Was waiting for this mod and now it's here! I love it much better than backpack mods, now I don't need to store a lot of unnecessary items or open my inventory all the time just to throw it away. Clean and good.
